// #Misfits Change - Whitelist Search admin panel code-behind
using System.Linq;
using System.Threading;
using Content.Client.UserInterface.Controls;
using Content.Shared._Misfits.Administration;
using Content.Shared.Roles;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Network;
using Robust.Shared.Prototypes;
using Timer = Robust.Shared.Timing.Timer;

namespace Content.Client._Misfits.Administration.UI;

[GenerateTypedNameReferences]
public sealed partial class WhitelistSearchWindow : FancyWindow
{
    [Dependency] private readonly IPrototypeManager _proto = default!;

    public Action<string>? OnSearch;
    public Action<NetUserId>? OnSelectPlayer;
    public Action<List<ProtoId<JobPrototype>>, bool>? OnSetJobs;

    private CancellationTokenSource? _searchDebounce;

    // #Misfits Change - Exclude vanilla SS14 departments; all Nuclear14/Misfits factions show automatically
    private static readonly HashSet<string> ExcludedDepartments = new()
    {
        "Logistics",
        "Civilian",
        "Command",
        "Dignitary",
        "Engineering",
        "Medical",
        "Security",
        "Epistemics",
        "Silicon",
        "Specific",
    };

    public WhitelistSearchWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        SearchBox.OnTextChanged += OnSearchTextChanged;
        SearchBox.OnTextEntered += OnSearchTextEntered;
        SearchButton.OnPressed += OnSearchButtonPressed;
        RoleSearchBox.OnTextChanged += OnRoleSearchTextChanged;
    }

    private void OnSearchButtonPressed(BaseButton.ButtonEventArgs args)
    {
        var query = SearchBox.Text.Trim();
        if (query.Length >= 2)
            OnSearch?.Invoke(query);
    }

    private void OnSearchTextEntered(LineEdit.LineEditEventArgs args)
    {
        _searchDebounce?.Cancel();
        var query = args.Text.Trim();
        if (query.Length >= 2)
            OnSearch?.Invoke(query);
    }

    private void OnSearchTextChanged(LineEdit.LineEditEventArgs args)
    {
        _searchDebounce?.Cancel();
        _searchDebounce = new CancellationTokenSource();

        var query = args.Text.Trim();
        if (query.Length < 2)
        {
            SearchResults.RemoveAllChildren();
            return;
        }

        Timer.Spawn(300, () =>
        {
            OnSearch?.Invoke(query);
        }, _searchDebounce.Token);
    }

    private void OnRoleSearchTextChanged(LineEdit.LineEditEventArgs args)
    {
        var filter = args.Text.Trim();
        foreach (var child in Departments.Children)
        {
            if (child is WhitelistDepartmentPanel panel)
                panel.Filter(filter);
        }
    }

    public void HandleState(WhitelistSearchEuiState state)
    {
        // Update search results
        SearchResults.RemoveAllChildren();
        foreach (var playerInfo in state.SearchResults)
        {
            var button = new Button
            {
                Text = playerInfo.UserName,
                HorizontalExpand = true,
            };
            var capturedId = playerInfo.UserId;
            button.OnPressed += _ => OnSelectPlayer?.Invoke(capturedId);
            SearchResults.AddChild(button);
        }

        // Update selected player whitelists
        if (state.SelectedPlayerName != null && state.Whitelists != null)
        {
            SelectedPlayerLabel.Text = $"Whitelists for: {state.SelectedPlayerName}";
            UpdateDepartments(state.Whitelists);
        }
        else
        {
            SelectedPlayerLabel.Text = "No player selected";
            Departments.RemoveAllChildren();
        }
    }

    private void UpdateDepartments(HashSet<ProtoId<JobPrototype>> whitelists)
    {
        Departments.RemoveAllChildren();
        var currentFilter = RoleSearchBox.Text.Trim();

        foreach (var proto in _proto.EnumeratePrototypes<DepartmentPrototype>()
                     .OrderByDescending(x => x.Weight)
                     .ThenBy(x => x.ID))
        {
            if (ExcludedDepartments.Contains(proto.ID))
                continue;

            var panel = new WhitelistDepartmentPanel(proto, _proto, whitelists);
            panel.OnSetJobs += (ids, whitelisting) => OnSetJobs?.Invoke(ids, whitelisting);
            if (!string.IsNullOrWhiteSpace(currentFilter))
                panel.Filter(currentFilter);
            Departments.AddChild(panel);
        }
    }
}
